#spring:
#  application:
#    name: gateway-server #微服务名称
#  cloud:
#    nacos:
#      username: nacos
#      password: nacos
#      config: #nacos配置中心
#        server-addr: 192.168.49.128:8848
#        namespace: 0f57359b-97d3-4223-878b-44e5aea53187 #${spring.cloud.nacos.discovery.namespace}
#        group: A_GROUP #${spring.cloud.nacos.discovery.group}
#        prefix: gateway-server #${spring.application.name}
#        file-extension: yml
#      discovery:
#        server-addr: 192.168.49.128:8848
#        enabled: true
#        namespace: 0f57359b-97d3-4223-878b-44e5aea53187
#        group: A_GROUP
#        service: gateway-server #${spring.application.name} # nacos注册中心配置
#  config:
#    activate:
#      on-profile: dev #多环境配置中心
#
############      nacos远程配置文件 ############
##
##server:
##  port: 80 #服务端口号, 网关默认80
##spring:
##    cloud:
##      gateway:
##        discovery:
##          locator:
##            enabled: true #开启gateway的动态路由，从nacos注册中心的服务列表获取服务名称，然后再动态路由到相对应的服务中去
##  redis: #redis配置
##    host: 192.168.49.128
##    port: 6380
##    password: 123456
